# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: <%= ENV['KAFKA_CLIENT_ID'] %>

development:
  <<: *common
  brokers:
    - <%= ENV['KAFKA_BROKER'] %>

test:
  <<: *common
  brokers:
    - <%= ENV['KAFKA_BROKER'] %>

production:
  <<: *common
  brokers:
    - kafka1.myapp.com:9092
    - kafka2.myapp.com:9092
    - kafka3.myapp.com:9092
